---
# tasks file for securcom.nftables

- name: "set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-default.yml"
  tags: nftables

- name: include packages tasks
  include_tasks: packages-{{ ansible_os_family }}.yml
  tags:
    - nftables
    - nftables:packages

- name: include config tasks
  include_tasks: config.yml
  tags:
    - nftables
    - nftables:config

- name: include service tasks
  include_tasks: service.yml
  tags:
    - nftables
    - nftables:service
